export enum Contrast {
	PAN_ANY = 0x00,
		PAN_NO_FIT = 0x01,
		PAN_CONTRAST_NONE = 0x02,
		PAN_CONTRAST_VERY_LOW = 0x03,
		PAN_CONTRAST_LOW = 0x04,
		PAN_CONTRAST_MEDIUM_LOW = 0x05,
		PAN_CONTRAST_MEDIUM = 0x06,
		PAN_CONTRAST_MEDIUM_HIGH = 0x07,
		PAN_CONTRAST_HIGH = 0x08,
		PAN_CONTRAST_VERY_HIGH = 0x09
}