export enum Letterform {
	PAN_ANY = 0x00,
	PAN_NO_FIT = 0x01,
	PAN_LETT_NORMAL_CONTACT = 0x02,
	PAN_LETT_NORMAL_WEIGHTED = 0x03,
	PAN_LETT_NORMAL_BOXED = 0x04,
	PAN_LETT_NORMAL_FLATTENED = 0x05,
	PAN_LETT_NORMAL_ROUNDED = 0x06,
	PAN_LETT_NORMAL_OFF_CENTER = 0x07,
	PAN_LETT_NORMAL_SQUARE = 0x08,
	PAN_LETT_OBLIQUE_CONTACT = 0x09,
	PAN_LETT_OBLIQUE_WEIGHTED = 0x0A,
	PAN_LETT_OBLIQUE_BOXED = 0x0B,
	PAN_LETT_OBLIQUE_FLATTENED = 0x0C,
	PAN_LETT_OBLIQUE_ROUNDED = 0x0D,
	PAN_LETT_OBLIQUE_OFF_CENTER = 0x0E,
	PAN_LETT_OBLIQUE_SQUARE = 0x0F
}