export enum MidLine {
	PAN_ANY = 0x00,
	PAN_NO_FIT = 0x01,
	PAN_MIDLINE_STANDARD_TRIMMED = 0x02,
	PAN_MIDLINE_STANDARD_POINTED = 0x03,
	PAN_MIDLINE_STANDARD_SERIFED = 0x04,
	PAN_MIDLINE_HIGH_TRIMMED = 0x05,
	PAN_MIDLINE_HIGH_POINTED = 0x06,
	PAN_MIDLINE_HIGH_SERIFED = 0x07,
	PAN_MIDLINE_CONSTANT_TRIMMED = 0x08,
	PAN_MIDLINE_CONSTANT_POINTED = 0x09,
	PAN_MIDLINE_CONSTANT_SERIFED = 0x0A,
	PAN_MIDLINE_LOW_TRIMMED = 0x0B,
	PAN_MIDLINE_LOW_POINTED = 0x0C,
	PAN_MIDLINE_LOW_SERIFED = 0x0D
}