export enum SerifType {
	PAN_ANY = 0x00,
	PAN_NO_FIT = 0x01,
	PAN_SERIF_COVE = 0x02,
	PAN_SERIF_OBTUSE_COVE = 0x03,
	PAN_SERIF_SQUARE_COVE = 0x04,
	PAN_SERIF_OBTUSE_SQUARE_COVE = 0x05,
	PAN_SERIF_SQUARE = 0x06,
	PAN_SERIF_THIN = 0x07,
	PAN_SERIF_BONE = 0x08,
	PAN_SERIF_EXAGGERATED = 0x09,
	PAN_SERIF_TRIANGLE = 0x0A,
	PAN_SERIF_NORMAL_SANS = 0x0B,
	PAN_SERIF_OBTUSE_SANS = 0x0C,
	PAN_SERIF_PERP_SANS = 0x0D,
	PAN_SERIF_FLARED = 0x0E,
	PAN_SERIF_ROUNDED = 0x0F
}