export enum StrokeVariation {
	PAN_ANY = 0x00,
	PAN_NO_FIT = 0x01,
	PAN_STROKE_GRADUAL_DIAG = 0x02,
	PAN_STROKE_GRADUAL_TRAN = 0x03,
	PAN_STROKE_GRADUAL_VERT = 0x04,
	PAN_STROKE_GRADUAL_HORZ = 0x05,
	PAN_STROKE_RAPID_VERT = 0x06,
	PAN_STROKE_RAPID_HORZ = 0x07,
	PAN_STROKE_INSTANT_VERT = 0x08
}
