export enum XHeight {
	PAN_ANY = 0x00,
	PAN_NO_FIT = 0x01,
	PAN_XHEIGHT_CONSTANT_SMALL = 0x02,
	PAN_XHEIGHT_CONSTANT_STD = 0x03,
	PAN_XHEIGHT_CONSTANT_LARGE = 0x04,
	PAN_XHEIGHT_DUCKING_SMALL = 0x05,
	PAN_XHEIGHT_DUCKING_STD = 0x06,
	PAN_XHEIGHT_DUCKING_LARGE = 0x07
}