export const PixelFormatDescriptor = {
	nSize: 16,
	nVersion: 16,
	dwFlags: 32,
	iPixelType: 1,
	cColorBits: 1,
	cRedBits: 1,
	cRedShift: 1,
	cGreenBits: 1,
	cGreenShift: 1,
	cBlueBits: 1,
	cBlueShift: 1,
	cAlphaBits: 1,
	cAlphaShift: 1,
	cAccumBits: 1,
	cAccumRedBits: 1,
	cAccumGreenBits: 1,
	cAccumBlueBits: 1,
	cAccumAlphaBits: 1,
	cDepthBits: 1,
	cStencilBits: 1,
	cAuxBuffers: 1,
	iLayerType: 1,
	bReserved: 1,
	dwLayerMask: 32,
	dwVisibleMask: 32,
	dwDamageMask: 32
};